
# This is a basic workflow that is manually triggered
# try to use as much shell scripting a possible
# actions appear from default branch - https://github.community/t/workflow-files-only-picked-up-from-master/16129/2
name: Test ACR deployment

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      tag:
        description: 'branch or tag'
        default: 'main'
        required: true
env:
  APP: test
  CR_HOST: my-acr-registry.ap-southeast-1.cr.aliyuncs.com
  CR_NS: es-labs
  USER_NAME: cicd_user
  DOCKERFILE_TARGET: uat
jobs:
  deploy_to_aliyun_acr:
    runs-on: ubuntu-latest
    name: Deploying To Aliyun ACR
    steps:
      - name: Selected Branch/tag
        run: |
          echo ${{ github.event.inputs.tag }}
      - name: Add checkout plugin
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Build and push image to ACR
        env:
          IMAGE_TARGET: main
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker login --username=${USER_NAME} --password=${{ secrets.ACR }} ${CR_HOST}
          docker build -t ${CR_HOST}/${CR_NS}/${APP}-api:latest --target $DOCKERFILE_TARGET --build-arg ARG_NODE_ENV=$DOCKERFILE_TARGET --build-arg ARG_API_PORT=3000 . || exit 1001
          docker push ${CR)_HOST}/${CR_NS}/${APP}-api:latest
